
model:
  base_learning_rate: 1.0
  target: taming.models.AbAgKer_newLLM.AbAgKerTrainer
  params:
    monitor: val/kd_rmse
    train_type: moe
    model_config:
      target: taming.modules.autoencoder.Model_newLLM.AbAgKerModel
      params:
        H_llm: /root/private_data/luog/pretrained_LLM/palm/Heavy_roformer
        L_llm: /root/private_data/luog/pretrained_LLM/palm/Light_roformer
        ems2_llm: /root/private_data/luog/AbAgKer/pretrain_LLM/esm2  # /root/private_data/luog/pretrained_LLM/esm2_t30
        ab_maxlen: 256 
        ag_maxlen: 896 
        dim: 512
        cdrs_layers: 4
        cdrs_heads: 16
        co_heads: 8
        ab_pool_nums: 64
        ag_pool_nums: 64
        ag_window: 9
        dp_out: 0.1
        num_experts: 4
        top_k: 2
    opt_config: 
      beta1: 0.9
      beta2: 0.999
      warm_up_steps: 100
      lr_min: 1.0e-6
      lr_max: 5.0e-5
      lr_start: 1.0e-7
      max_decay_steps: 1000 # 1350//8 * 50 = 8400
      verbosity_interval: 10
    loss_config:
      target: taming.modules.losses.loss_Ab.CELoss 
      params:
        kd_weight: 1.0
        koff_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    train:
      target: taming.data.PM_Data.DataTrain
      params:
        training_list_file: /root/private_data/luog/AbAgKer/data/AbAgA_byPDB/fold_2_train.json
    validation:
      target: taming.data.PM_Data.DataVal
      params:
        val_list_file: /root/private_data/luog/AbAgKer/data/AbAgA_byPDB/fold_2_test.json
